services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmq-namesrv
    ports:
      - "9876:9876"
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    environment:
      - JAVA_OPT=-Xms512m -Xmx512m
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:5.3.2
    container_name: rmq-broker
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./conf/broker.conf:/home/rocketmq/conf/broker.conf
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPT=-Xms1g -Xmx1g
    depends_on:
      - namesrv
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmq-dashboard
    ports:
      - "8180:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - namesrv