server:
  port: 9090
spring:
  cloud:
    function.definition: orderHandler
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        orderHandler-in-0:
          destination: order-event
          group: order-handler-group
  datasource:
    url: jdbc:h2:mem:hi_db;MODE=POSTGRESQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: h2
logging:
  level:
    root: info
