server:
  port: 9000
  servlet:
    context-path: /ex1

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=POSTGRESQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
