spring:
  cloud:
    openfeign:
      client:
        config:
          # 全局默认配置 (所有 feign client 生效)
          default:
            logger-level: full
          # 指定 feign client 生效
          service_name:
            logger-level: full
            read-timeout: 5000
            connect-timeout: 5000

