services:
  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUX_ADMIN_ENABLED=true
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
volumes:
  influxdb_data:

